#!/bin/sh

local=$1
remote=$2

cd "$local" &&
#fswatch . "date +%H:%M:%S && rsync -aztH --exclude '#*' --exclude .git --exclude .svn --progress --rsh='ssh -p22' . $remote"
alias run_rsync="date && rsync -aztH --exclude bin --exclude out --exclude test_out --delete --progress . $remote"
run_rsync; fswatch -o . | while read f; do run_rsync; done
